### ISSUE TITLE
Error In $pio Build (Repo.TypeSafe.com moved Temporarily) 

### ISSUE THREAD

**Issue by shivpal0102** [mingfang/docker-predictionio#27] opened 2017-05-04 08:43 UTC
I have Followed the given steps but when i run the run.sh command Following Error came.

HTTP/1.1 302 Moved Temporarily

Full Error is inside the attached File.

[Error-File.txt](https://github.com/mingfang/docker-predictionio/files/975580/Error-File.txt)

After this Error When I run `$ pio train` the following Error Came
```

[ERROR] [Executor] Exception in task 0.0 in stage 39.0 (TID 60)
[ERROR] [Executor] Exception in task 1.0 in stage 39.0 (TID 61)
[WARN] [TaskSetManager] Lost task 1.0 in stage 39.0 (TID 61, localhost): java.lang.StackOverflowError
```
And 

```
[ERROR] [TaskSetManager] Task 1 in stage 39.0 failed 1 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task1 in stage 39.0 failed 1 times, most recent failure: Lost task 1.0 in stage 39.0 (TID 61, localhost): java.lang.StackOverflowError
```

I have also followed the Steps given at:
http://predictionio.incubator.apache.org/templates/recommendation/quickstart/

But same thing happens at : $ pio build --verbose. and Pio train.

**Comment by mingfang** [comment] 2017-12-11 06:15
I'm guessing this was a temporary issue caused by changes in the public repo.
Closing for now.
Feel free to reopen if this is still a problem.

**Closed by mingfang** 2017-12-11 06:15 UTC
